services:
  redis:
    image: redis
    ports:
      - "127.0.0.1:6380:6379"
    user: "redis:redis"
  postgres:
    image: pgvector/pgvector:pg17
    container_name: postgres_ba_agent
    ports:
      - "127.0.0.1:5431:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: outline-ba-agent
    user: "postgres:postgres"
    volumes:
      - postgres_data_ba_agent:/var/lib/postgresql/data

volumes:
  postgres_data_ba_agent:
